
const Details=[
    {
        id:1,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:2,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:3,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:4,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:5,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:6,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:7,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:8,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:9,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:10,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
    {
        id:11,
        title:"DARK",
        imgsrc:"https://resizing.flixster.com/xvfdB-xK1Ec8AkRnBZFSZiRhTWo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjUxNTIxNC53ZWJw",
        website:"https://www.netflix.com/in/title/80100172"
    },
]



export default Details